In [ ]:
# @title
!pip install pdfplumber

Collecting pdfplumber
  Downloading pdfplumber-0.11.9-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.8 MB/s eta 0:00:00
Collecting pdfminer.six==20251230 (from pdfplumber)
  Downloading pdfminer_six-20251230-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-5.7.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.9/67.9 kB 4.8 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (3.4.6)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (3.0)
Downloading pdfplumber-0.11.9-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 4.6 MB/s eta 0:00:00
Downloading pdfminer_six-20251230-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 63.1 MB/s eta 0:00:00
Downloading pypdfium2-5.7.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 100.3 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20251230 pdfplumber-0.11.9 pypdfium2-5.7.0

In [ ]:
import pdfplumber
import pandas as pd

pdf_path = "/content/seleksi adm.pdf"

filtered_tables = []

with pdfplumber.open(pdf_path) as pdf:
    for i, page in enumerate(pdf.pages):
        table = page.extract_table()

        if table:
            df = pd.DataFrame(table[1:], columns=table[0])

            # Normalize column count (handle None headers)
            num_cols = len(df.columns)

            if num_cols == 7:
                print(f"Page {i+1}: ✅ Lanjut (7 columns)")
                filtered_tables.append(df)
            else:
                print(f"Page {i+1}: ❌ Skip ah ({num_cols} columns)")

# Merge all valid tables
if filtered_tables:
    df1 = pd.concat(filtered_tables, ignore_index=True)
else:
    df1 = pd.DataFrame()

print("Final shape:", df1.shape)

df1.to_excel("df1_original_file.xlsx", index=False)

In [ ]:
df1.head()

,NO,NOMOR REGISTRASI,NAMA PELAMAR,JENIS\nKELAMIN,JABATAN YANG DILAMAR,UNIT PENEMPATAN YANG DILAMAR,KETERANGAN
0,1,6116111848928696,A AZFIKAR NUR AZHAR,Pria,PENGELOLA LAYANAN KESEHATAN,PEMERINTAH DAERAH PROVINSI JAWA BARAT | DINAS ...,Memenuhi Syarat / MS
1,2,6100118716575747,A FAISYAL RACHMAN JP,Pria,PENGELOLA PENGADAAN BARANG/JASA AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...,Memenuhi Syarat / MS
2,3,6100124600583863,A HIDAYANTI,Wanita,PENATA KELOLA LAYANAN KESEHATAN,PEMERINTAH DAERAH PROVINSI JAWA BARAT | DINAS ...,Memenuhi Syarat / MS
3,4,6100113674366924,A MAULANA MUKHSIN,Pria,PERENCANA AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | DINAS ...,Memenuhi Syarat / MS
4,5,6100110392034262,A MULQI FADILAH A,Pria,PENGENDALI DAMPAK LINGKUNGAN AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | DINAS ...,Tidak Memenuhi Syarat / TMS

In [ ]:
df1_ = df1.copy()
df1.drop(columns={"NO"}, inplace=True)

In [ ]:
df1.head()

,NOMOR REGISTRASI,NAMA PELAMAR,JENIS\nKELAMIN,JABATAN YANG DILAMAR,UNIT PENEMPATAN YANG DILAMAR,KETERANGAN
0,6116111848928696,A AZFIKAR NUR AZHAR,Pria,PENGELOLA LAYANAN KESEHATAN,PEMERINTAH DAERAH PROVINSI JAWA BARAT | DINAS ...,Memenuhi Syarat / MS
1,6100118716575747,A FAISYAL RACHMAN JP,Pria,PENGELOLA PENGADAAN BARANG/JASA AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...,Memenuhi Syarat / MS
2,6100124600583863,A HIDAYANTI,Wanita,PENATA KELOLA LAYANAN KESEHATAN,PEMERINTAH DAERAH PROVINSI JAWA BARAT | DINAS ...,Memenuhi Syarat / MS
3,6100113674366924,A MAULANA MUKHSIN,Pria,PERENCANA AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | DINAS ...,Memenuhi Syarat / MS
4,6100110392034262,A MULQI FADILAH A,Pria,PENGENDALI DAMPAK LINGKUNGAN AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | DINAS ...,Tidak Memenuhi Syarat / TMS

In [7]:
df1.rename(columns={'NOMOR REGISTRASI': 'No Peserta',
                    'NAMA PELAMAR': 'Nama',
                    'JENIS\nKELAMIN': 'Jenis Kelamin',
                    'JABATAN YANG DILAMAR': 'Formasi',
                    'UNIT PENEMPATAN YANG DILAMAR': 'Penempatan',
                    'KETERANGAN': 'Ket'}, inplace=True)

In [10]:
df1 = df1[df1['Ket'] == 'Memenuhi Syarat / MS']

In [51]:
df2 = pd.read_excel('/content/Data Integrasi SKD SKB.xlsx')
df2.head(5)

,No Peserta,Nama,Tanggal Lahir,Pendidikan,IPK,TWK,TIU,TKP,SKD,SKD 40%,SKB,SKB 60%,Nilai Akhir,Keterangan
0,24610020110001372,M. NAUVAL MAHRAN AZIZ,24 Desember 2001,S-1 HUKUM,3.84,95,150,190,435,31.636,74.0,44.4,76.036,P/L
1,24610020120003261,DINI SITI RUKMINI,20 Mei 1998,S-1 HUKUM,3.79,100,140,194,434,31.564,73.0,43.8,75.364,P/L
2,24610020120007450,KHALDA ALIFIA AZZAHRA,26 Maret 2002,S-1 HUKUM,3.92,100,160,180,440,32.000,70.0,42.0,74.000,TL
3,24610020120006233,GITA RANJANI,10 Desember 1999,S-1 HUKUM,3.86,95,135,189,419,30.473,67.0,40.2,70.673,TL
4,24610020120001056,ZAHRA NABILA SUKMANA,24 April 2001,S-1 HUKUM,3.56,90,125,185,400,29.091,53.0,31.8,60.891,TL

In [52]:
df1.head(5)

,No Peserta,Nama,Jenis Kelamin,Formasi,Penempatan,Ket
0,6116111848928696,A AZFIKAR NUR AZHAR,Pria,PENGELOLA LAYANAN KESEHATAN,PEMERINTAH DAERAH PROVINSI JAWA BARAT | DINAS ...,Memenuhi Syarat / MS
1,6100118716575747,A FAISYAL RACHMAN JP,Pria,PENGELOLA PENGADAAN BARANG/JASA AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...,Memenuhi Syarat / MS
2,6100124600583863,A HIDAYANTI,Wanita,PENATA KELOLA LAYANAN KESEHATAN,PEMERINTAH DAERAH PROVINSI JAWA BARAT | DINAS ...,Memenuhi Syarat / MS
3,6100113674366924,A MAULANA MUKHSIN,Pria,PERENCANA AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | DINAS ...,Memenuhi Syarat / MS
6,6100111112650304,A SAEFUL ANWAR,Pria,ANALIS PASAR HASIL PERTANIAN TERAMPIL,PEMERINTAH DAERAH PROVINSI JAWA BARAT | DINAS ...,Memenuhi Syarat / MS

In [53]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20277 entries, 0 to 22954
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   No Peserta     20277 non-null  int64
 1   Nama           20277 non-null  object
 2   Jenis Kelamin  20277 non-null  object
 3   Formasi        20277 non-null  object
 4   Penempatan     20277 non-null  object
 5   Ket            20277 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.1+ MB

In [54]:
df1['No Peserta'] = df1['No Peserta'].astype('int64')

df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20277 entries, 0 to 22954
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   No Peserta     20277 non-null  int64
 1   Nama           20277 non-null  object
 2   Jenis Kelamin  20277 non-null  object
 3   Formasi        20277 non-null  object
 4   Penempatan     20277 non-null  object
 5   Ket            20277 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.1+ MB

In [56]:
df_gabung = df2.merge(
    df1[['Nama', 'Jenis Kelamin', 'Formasi', 'Penempatan',]],  # only needed columns
    on='Nama',
    how='left'
)

df_gabung.head(5)

,No Peserta,Nama,Tanggal Lahir,Pendidikan,IPK,TWK,TIU,TKP,SKD,SKD 40%,SKB,SKB 60%,Nilai Akhir,Keterangan,Jenis Kelamin,Formasi,Penempatan
0,24610020110001372,M. NAUVAL MAHRAN AZIZ,24 Desember 2001,S-1 HUKUM,3.84,95,150,190,435,31.636,74.0,44.4,76.036,P/L,NaN,NaN,NaN
1,24610020120003261,DINI SITI RUKMINI,20 Mei 1998,S-1 HUKUM,3.79,100,140,194,434,31.564,73.0,43.8,75.364,P/L,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...
2,24610020120007450,KHALDA ALIFIA AZZAHRA,26 Maret 2002,S-1 HUKUM,3.92,100,160,180,440,32.000,70.0,42.0,74.000,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...
3,24610020120006233,GITA RANJANI,10 Desember 1999,S-1 HUKUM,3.86,95,135,189,419,30.473,67.0,40.2,70.673,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...
4,24610020120001056,ZAHRA NABILA SUKMANA,24 April 2001,S-1 HUKUM,3.56,90,125,185,400,29.091,53.0,31.8,60.891,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...

In [57]:
df1[df1['Nama'].str.contains('MAHRAN')]

,No Peserta,Nama,Jenis Kelamin,Formasi,Penempatan,Ket
3903,6100120449066272,CAMELIA ROSI MAHRANI,Wanita,FASILITATOR PEMERINTAHAN,PEMERINTAH DAERAH PROVINSI JAWA BARAT | DINAS ...,Memenuhi Syarat / MS
13588,6100111329179857,MUHAMMAD NAUVAL MAHRAN AZIS,Pria,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...,Memenuhi Syarat / MS

In [58]:
df2[df2['Nama'].str.contains('MAHRAN')]

,No Peserta,Nama,Tanggal Lahir,Pendidikan,IPK,TWK,TIU,TKP,SKD,SKD 40%,SKB,SKB 60%,Nilai Akhir,Keterangan
0,24610020110001372,M. NAUVAL MAHRAN AZIZ,24 Desember 2001,S-1 HUKUM,3.84,95,150,190,435,31.636,74.0,44.4,76.036,P/L

In [59]:
df_gabung[df_gabung['Formasi'].isna()].head(5)

,No Peserta,Nama,Tanggal Lahir,Pendidikan,IPK,TWK,TIU,TKP,SKD,SKD 40%,SKB,SKB 60%,Nilai Akhir,Keterangan,Jenis Kelamin,Formasi,Penempatan
0,24610020110001372,M. NAUVAL MAHRAN AZIZ,24 Desember 2001,S-1 HUKUM,3.84,95,150,190,435,31.636,74.0,44.4,76.036,P/L,NaN,NaN,NaN
10,24610020110003022,AMALUL ARIFIN FADHLI,19 September 1994,S-1 HUKUM,3.49,100,110,187,397,28.873,68.0,40.8,69.673,P/L,NaN,NaN,NaN
21,24610020110001570,RADEN MUHAMMAD REZKY KAMIL,25 Juli 1997,S-1 HUKUM,3.47,95,130,199,424,30.836,65.0,39.0,69.836,TL,NaN,NaN,NaN
28,24610020120007417,RANI AULIA FITRIANI,17 November 1996,S-1 HUKUM,3.81,85,90,193,368,26.764,50.0,30.0,56.764,TL,NaN,NaN,NaN
41,24610020120005320,DR. NENG LILIS NUR HASANAH,02 Februari 1993,PROFESI DOKTER,3.38,80,95,191,366,26.618,73.0,43.8,70.418,TL,NaN,NaN,NaN

In [60]:
!pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 30.9 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.5

In [70]:
import pandas as pd
from rapidfuzz import process, fuzz

# Install dulu jika belum: pip install rapidfuzz

def fuzzy_merge(df2, df1, col='Nama', threshold=0):
    """
    Merge df2 dengan df1 menggunakan fuzzy matching pada kolom Nama.
    threshold: skor kecocokan minimum (0-100), makin tinggi makin ketat
    """

    # Kolom dari df1 yang ingin ditambahkan ke df2
    cols_to_add = ['Jenis Kelamin', 'Formasi', 'Penempatan']

    matched_rows = []

    for nama in df2[col]:
        # Cari nama paling mirip di df1
        result = process.extractOne(
            nama,
            df1[col].tolist(),
            scorer=fuzz.token_sort_ratio  # Bagus untuk nama yang urutannya berbeda
        )

        if result and result[1] >= threshold:
            matched_nama = result[0]
            score = result[1]
            row = df1[df1[col] == matched_nama][cols_to_add].iloc[0].to_dict()
            row['_matched_nama'] = matched_nama  # Untuk verifikasi
            row['_match_score'] = score
        else:
            # Tidak ditemukan kecocokan
            row = {c: None for c in cols_to_add}
            row['_matched_nama'] = None
            row['_match_score'] = None

        matched_rows.append(row)

    result_df = pd.DataFrame(matched_rows)
    df2 = pd.concat([df2.reset_index(drop=True), result_df], axis=1)
    return df2


# Jalankan
df2_merged = fuzzy_merge(df2, df1, threshold=80)

# Cek hasil — terutama yang score-nya tidak 100 (perlu diverifikasi manual)
print(df2_merged[['Nama', '_matched_nama', '_match_score']].sort_values('_match_score'))

                                    Nama                        _matched_nama  \
1135         M.RIFKI PRADILA NUSANTARA K         M. RIFKI PRADILA NUSANTARA K
51                   IRMA RIZKI HIDAYATI                RIZKI MAURIZA HIDAYAT
788                    RIKE APRILIANI.AS                   RIKE APRILIANI .AS
178               TSULATSY PUSPITASARI P    TSULATSY PUSPITASARI PURNAMIHARJA
951   MUHAMMAD GHIFARI ALSYAUQI RAMSARAN  MUHAMMAD GHIFARI AL SYAUQI RAMSARAN
...                                  ...                                  ...
1626                 H AQIIM MOH PANDEGO                                 None
1673             ABIGHAIL SHAFIRA IHSANI                                 None
1773          HARIS JONATHAN, AMD LLASDP                                 None
1781             ALBERTUS RHIDY OCTAVISA                                 None
1867                 SHANIA MAULI PATRIA                                 None

      _match_score
1135      80.00000
51        80.00000
788       80.00000
178       80.00000
951       81.15942
...            ...
1626           NaN
1673           NaN
1773           NaN
1781           NaN
1867           NaN

[1883 rows x 3 columns]

In [71]:
df2_merged.head(5)

,No Peserta,Nama,Tanggal Lahir,Pendidikan,IPK,TWK,TIU,TKP,SKD,SKD 40%,SKB,SKB 60%,Nilai Akhir,Keterangan,Jenis Kelamin,Formasi,Penempatan,_matched_nama,_match_score
0,24610020110001372,M. NAUVAL MAHRAN AZIZ,24 Desember 2001,S-1 HUKUM,3.84,95,150,190,435,31.636,74.0,44.4,76.036,P/L,None,None,None,None,NaN
1,24610020120003261,DINI SITI RUKMINI,20 Mei 1998,S-1 HUKUM,3.79,100,140,194,434,31.564,73.0,43.8,75.364,P/L,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...,DINI SITI RUKMINI,100.0
2,24610020120007450,KHALDA ALIFIA AZZAHRA,26 Maret 2002,S-1 HUKUM,3.92,100,160,180,440,32.000,70.0,42.0,74.000,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...,KHALDA ALIFIA AZZAHRA,100.0
3,24610020120006233,GITA RANJANI,10 Desember 1999,S-1 HUKUM,3.86,95,135,189,419,30.473,67.0,40.2,70.673,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...,GITA RANJANI,100.0
4,24610020120001056,ZAHRA NABILA SUKMANA,24 April 2001,S-1 HUKUM,3.56,90,125,185,400,29.091,53.0,31.8,60.891,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...,ZAHRA NABILA SUKMANA,100.0

In [95]:
# Lihat yang perlu diverifikasi manual
df2_merged[df2_merged['_match_score'].isnull()][['Nama', 'Formasi', '_matched_nama', '_match_score']]

                               Nama Formasi _matched_nama  _match_score
0             M. NAUVAL MAHRAN AZIZ    None          None           NaN
10             AMALUL ARIFIN FADHLI    None          None           NaN
61                      FENY RENITA    None          None           NaN
94        DIAN KUSUMAH, S.T., M.HAN    None          None           NaN
124                  RIZA PAMUNGKAS    None          None           NaN
135         HAFIDZ ILYAS ATH-THARIQ    None          None           NaN
137            RIZAL LESMANA, S.PT.    None          None           NaN
165                  RIZAL GUSDINAR    None          None           NaN
193                      NUR INAYAH    None          None           NaN
285                    ZAID MAHMUDI    None          None           NaN
358         RD SANDRA CHAERUN NISSA    None          None           NaN
380              DITA FAUZIA, S.KOM    None          None           NaN
388          RAFLY SYAH RIZAL AKBAR    None          None           NaN
412   R.M.KUNTA LAMONA WIRIASAPUTRA    None          None           NaN
528       ANITA NADHILA, S.H., M.H.    None          None           NaN
629                   ARISANDI, S.T    None          None           NaN
669                         ELIYANI    None          None           NaN
771                    FAIRO BAGOES    None          None           NaN
853   SANDI PUTRA PERDANA, A.MD.KOM    None          None           NaN
860                  REVY SHAFIRA A    None          None           NaN
972            ANITA ZAHRA NUR AINI    None          None           NaN
1147         FRITS LYNDON WASSAHDAD    None          None           NaN
1313          ALDILA DELFANI HAFIDZ    None          None           NaN
1581        MOCH.FAKHRI DWI PRABOWO    None          None           NaN
1600           ULDA RAHMA DILA,S.IP    None          None           NaN
1626            H AQIIM MOH PANDEGO    None          None           NaN
1673        ABIGHAIL SHAFIRA IHSANI    None          None           NaN
1773     HARIS JONATHAN, AMD LLASDP    None          None           NaN
1781        ALBERTUS RHIDY OCTAVISA    None          None           NaN
1867            SHANIA MAULI PATRIA    None          None           NaN

In [94]:
df2_merged.head(5)

,No Peserta,Nama,Tanggal Lahir,Pendidikan,IPK,TWK,TIU,TKP,SKD,SKD 40%,SKB,SKB 60%,Nilai Akhir,Keterangan,Jenis Kelamin,Formasi,Penempatan,_matched_nama,_match_score
0,24610020110001372,M. NAUVAL MAHRAN AZIZ,24 Desember 2001,S-1 HUKUM,3.84,95,150,190,435,31.636,74.0,44.4,76.036,P/L,None,None,None,None,NaN
1,24610020120003261,DINI SITI RUKMINI,20 Mei 1998,S-1 HUKUM,3.79,100,140,194,434,31.564,73.0,43.8,75.364,P/L,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...,DINI SITI RUKMINI,100.0
2,24610020120007450,KHALDA ALIFIA AZZAHRA,26 Maret 2002,S-1 HUKUM,3.92,100,160,180,440,32.000,70.0,42.0,74.000,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...,KHALDA ALIFIA AZZAHRA,100.0
3,24610020120006233,GITA RANJANI,10 Desember 1999,S-1 HUKUM,3.86,95,135,189,419,30.473,67.0,40.2,70.673,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...,GITA RANJANI,100.0
4,24610020120001056,ZAHRA NABILA SUKMANA,24 April 2001,S-1 HUKUM,3.56,90,125,185,400,29.091,53.0,31.8,60.891,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...,ZAHRA NABILA SUKMANA,100.0

In [97]:
df2_final = df2_merged.drop(columns=['_matched_nama', '_match_score'])
df2_final.head(5)

,No Peserta,Nama,Tanggal Lahir,Pendidikan,IPK,TWK,TIU,TKP,SKD,SKD 40%,SKB,SKB 60%,Nilai Akhir,Keterangan,Jenis Kelamin,Formasi,Penempatan
0,24610020110001372,M. NAUVAL MAHRAN AZIZ,24 Desember 2001,S-1 HUKUM,3.84,95,150,190,435,31.636,74.0,44.4,76.036,P/L,None,None,None
1,24610020120003261,DINI SITI RUKMINI,20 Mei 1998,S-1 HUKUM,3.79,100,140,194,434,31.564,73.0,43.8,75.364,P/L,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...
2,24610020120007450,KHALDA ALIFIA AZZAHRA,26 Maret 2002,S-1 HUKUM,3.92,100,160,180,440,32.000,70.0,42.0,74.000,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...
3,24610020120006233,GITA RANJANI,10 Desember 1999,S-1 HUKUM,3.86,95,135,189,419,30.473,67.0,40.2,70.673,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...
4,24610020120001056,ZAHRA NABILA SUKMANA,24 April 2001,S-1 HUKUM,3.56,90,125,185,400,29.091,53.0,31.8,60.891,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...

In [106]:
df2_final = df2_final.fillna('-')
df2_final.head(5)

,No Peserta,Nama,Tanggal Lahir,Pendidikan,IPK,TWK,TIU,TKP,SKD,SKD 40%,SKB,SKB 60%,Nilai Akhir,Keterangan,Jenis Kelamin,Formasi,Penempatan
0,24610020110001372,M. NAUVAL MAHRAN AZIZ,24 Desember 2001,S-1 HUKUM,3.84,95,150,190,435,31.636,74.0,44.4,76.036,P/L,-,-,-
1,24610020120003261,DINI SITI RUKMINI,20 Mei 1998,S-1 HUKUM,3.79,100,140,194,434,31.564,73.0,43.8,75.364,P/L,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...
2,24610020120007450,KHALDA ALIFIA AZZAHRA,26 Maret 2002,S-1 HUKUM,3.92,100,160,180,440,32.000,70.0,42.0,74.000,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...
3,24610020120006233,GITA RANJANI,10 Desember 1999,S-1 HUKUM,3.86,95,135,189,419,30.473,67.0,40.2,70.673,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...
4,24610020120001056,ZAHRA NABILA SUKMANA,24 April 2001,S-1 HUKUM,3.56,90,125,185,400,29.091,53.0,31.8,60.891,TL,Wanita,ANALIS HUKUM AHLI PERTAMA,PEMERINTAH DAERAH PROVINSI JAWA BARAT | SEKRET...

In [107]:
df2_final.to_excel('Hasil Seleksi Merged.xlsx', index=False)